/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AboutDialog.java
 *
 * Created on 30 nov. 2010, 22:42:50
 */

package feuille.karaoke.dialog;

import feuille.lib.Language;

/**
 * <p>This is a dialog which display informations.<br />
 * C'est une boîte de dialogue qui montre des informations.</p>
 * @author The Wingate 2940
 */
public class AboutDialog extends javax.swing.JDialog {

    private Language localeLanguage = feuille.MainFrame.getLanguage();

    /** <p>Creates new form AboutDialog.<br />
     * Crée un nouveau formulaire AboutDialog.</p> */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();        
        
        if(localeLanguage.getValueOf("titleABT")!=null){setTitle(localeLanguage.getValueOf("titleABT"));}
        if(localeLanguage.getValueOf("messAbout")!=null){lblAFMMessage.setText(localeLanguage.getValueOf("messAbout"));}
        if(localeLanguage.getValueOf("labelUsedByAFM")!=null){lblUsedByAFM.setText(localeLanguage.getValueOf("labelUsedByAFM"));}
        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblAssFxMaker = new javax.swing.JLabel();
        lblAFMMessage = new javax.swing.JLabel();
        lblAFMLink = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblUsedByAFM = new javax.swing.JLabel();
        lblJRuby = new javax.swing.JLabel();
        lblCrystalClear = new javax.swing.JLabel();
        lblJSyntaxPane = new javax.swing.JLabel();
        lblCurveCreator = new javax.swing.JLabel();
        lblJython = new javax.swing.JLabel();
        lblJFreeChart = new javax.swing.JLabel();
        lblROME = new javax.swing.JLabel();
        lblJMF = new javax.swing.JLabel();
        lblJDOM = new javax.swing.JLabel();
        lblFreefont = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About AssFxMaker");
        setAlwaysOnTop(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setLayout(null);

        lblAssFxMaker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feuille/lib/FeuilleGen3.png"))); // NOI18N
        lblAssFxMaker.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAssFxMaker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAssFxMakerMouseClicked(evt);
            }
        });
        jPanel1.add(lblAssFxMaker);
        lblAssFxMaker.setBounds(0, 0, 510, 260);

        lblAFMMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAFMMessage.setText("<html><p align=\"center\"><b>Feuille</b> (Funsub project 2006-2014).<br />GNU/GPLv3 - Free and open for all. <br />Feuille is made to think differently on Windows, Linux and Mac OS X.<br /><i><b>Developed by The Wingate 2940.<br />Contact at assfxmaker@gmail.com</b></i></p>");
        lblAFMMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAFMMessageMouseClicked(evt);
            }
        });
        jPanel1.add(lblAFMMessage);
        lblAFMMessage.setBounds(10, 260, 490, 90);

        lblAFMLink.setForeground(new java.awt.Color(0, 0, 255));
        lblAFMLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAFMLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feuille/images/20px-Crystal_Clear_app_internet.png"))); // NOI18N
        lblAFMLink.setText("https://github.com/TW2/Feuille");
        lblAFMLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAFMLinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAFMLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAFMLinkMouseExited(evt);
            }
        });
        jPanel1.add(lblAFMLink);
        lblAFMLink.setBounds(10, 360, 490, 14);

        jTabbedPane1.addTab("Feuille", jPanel1);

        lblUsedByAFM.setText("Used by Feuille : ");

        lblJRuby.setForeground(new java.awt.Color(0, 0, 255));
        lblJRuby.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feuille/images/20px-Crystal_Clear_app_internet.png"))); // NOI18N
        lblJRuby.setText("JRuby - http://jruby.org/");
        lblJRuby.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJRubyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblJRubyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblJRubyMouseExited(evt);
            }
        });

        lblCrystalClear.setForeground(new java.awt.Color(0, 0, 255));
        lblCrystalClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feuille/images/20px-Crystal_Clear_app_internet.png"))); // NOI18N
        lblCrystalClear.setText("Crystal Clear - http://commons.wikimedia.org/wiki/Crystal_Clear");
        lblCrystalClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCrystalClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCrystalClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCrystalClearMouseExited(evt);
            }
        });

        lblJSyntaxPane.setForeground(new java.awt.Color(0, 0, 255));
        lblJSyntaxPane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feuille/images/20px-Crystal_Clear_app_internet.png"))); // NOI18N
        lblJSyntaxPane.setText("JSyntaxePane - http://code.google.com/p/jsyntaxpane/");
        lblJSyntaxPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJSyntaxPaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblJSyntaxPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblJSyntaxPaneMouseExited(evt);
            }
        });

        lblCurveCreator.setForeground(java.awt.Color.blue);
        lblCurveCreator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feuille/images/20px-Crystal_Clear_app_internet.png"))); // NOI18N
        lblCurveCreator.setText("curvecreator - http://code.google.com/p/curvecreator/");
        lblCurveCreator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCurveCreatorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCurveCreatorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCurveCreatorMouseExited(evt);
            }
        });

        lblJython.setForeground(new java.awt.Color(0, 0, 255));
        lblJython.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feuille/images/20px-Crystal_Clear_app_internet.png"))); // NOI18N
        lblJython.setText("Jython - http://www.jython.org/");
        lblJython.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJythonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblJythonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblJythonMouseExited(evt);
            }
        });

        lblJFreeChart.setForeground(new java.awt.Color(0, 0, 255));
        lblJFreeChart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feuille/images/20px-Crystal_Clear_app_internet.png"))); // NOI18N
        lblJFreeChart.setText("JFreeChart - http://www.jfree.org/jfreechart/");
        lblJFreeChart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJFreeChartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblJFreeChartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblJFreeChartMouseExited(evt);
            }
        });

        lblROME.setForeground(new java.awt.Color(0, 0, 255));
        lblROME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feuille/images/20px-Crystal_Clear_app_internet.png"))); // NOI18N
        lblROME.setText("ROME - https://rometools.jira.com/wiki/display/ROME/Home");
        lblROME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblROMEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblROMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblROMEMouseExited(evt);
            }
        });

        lblJMF.setForeground(new java.awt.Color(0, 0, 255));
        lblJMF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feuille/images/20px-Crystal_Clear_app_internet.png"))); // NOI18N
        lblJMF.setText("JMF - http://www.oracle.com/technetwork/java/javase/download-142937.html");
        lblJMF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJMFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblJMFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblJMFMouseExited(evt);
            }
        });

        lblJDOM.setForeground(new java.awt.Color(0, 0, 255));
        lblJDOM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feuille/images/20px-Crystal_Clear_app_internet.png"))); // NOI18N
        lblJDOM.setText("JDOM - http://www.jdom.org/");
        lblJDOM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJDOMMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblJDOMMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblJDOMMouseExited(evt);
            }
        });

        lblFreefont.setForeground(new java.awt.Color(0, 0, 255));
        lblFreefont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feuille/images/20px-Crystal_Clear_app_internet.png"))); // NOI18N
        lblFreefont.setText("Free UCS Outline Fonts - http://savannah.gnu.org/projects/freefont/");
        lblFreefont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFreefontMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFreefontMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFreefontMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsedByAFM)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJFreeChart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblJython, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblJRuby, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                            .addComponent(lblCurveCreator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCrystalClear)
                                    .addComponent(lblJSyntaxPane))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblROME, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                            .addComponent(lblJMF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblJDOM, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                            .addComponent(lblFreefont, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsedByAFM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJRuby)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCrystalClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJSyntaxPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCurveCreator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJython)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJFreeChart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblROME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJMF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJDOM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFreefont)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("+", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        dispose();
    }//GEN-LAST:event_formMouseClicked

    private void lblJythonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJythonMouseExited
        lblJython.setText("Jython - http://www.jython.org/");
    }//GEN-LAST:event_lblJythonMouseExited

    private void lblJythonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJythonMouseEntered
        lblJython.setText("<html>Jython - <u>http://www.jython.org/");
    }//GEN-LAST:event_lblJythonMouseEntered

    private void lblJythonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJythonMouseClicked
        launchLink("http://www.jython.org/");
    }//GEN-LAST:event_lblJythonMouseClicked

    private void lblCurveCreatorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCurveCreatorMouseExited
        lblCurveCreator.setText("curvecreator - http://code.google.com/p/curvecreator/");
    }//GEN-LAST:event_lblCurveCreatorMouseExited

    private void lblCurveCreatorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCurveCreatorMouseEntered
        lblCurveCreator.setText("<html>curvecreator - <u>http://code.google.com/p/curvecreator/");
    }//GEN-LAST:event_lblCurveCreatorMouseEntered

    private void lblCurveCreatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCurveCreatorMouseClicked
        launchLink("http://code.google.com/p/curvecreator/");
    }//GEN-LAST:event_lblCurveCreatorMouseClicked

    private void lblJSyntaxPaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJSyntaxPaneMouseExited
        lblJSyntaxPane.setText("JSyntaxePane - http://code.google.com/p/jsyntaxpane/");
    }//GEN-LAST:event_lblJSyntaxPaneMouseExited

    private void lblJSyntaxPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJSyntaxPaneMouseEntered
        lblJSyntaxPane.setText("<html>JSyntaxePane - <u>http://code.google.com/p/jsyntaxpane/");
    }//GEN-LAST:event_lblJSyntaxPaneMouseEntered

    private void lblJSyntaxPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJSyntaxPaneMouseClicked
        launchLink("http://code.google.com/p/jsyntaxpane/");
    }//GEN-LAST:event_lblJSyntaxPaneMouseClicked

    private void lblCrystalClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrystalClearMouseExited
        lblCrystalClear.setText("Crystal Clear - http://commons.wikimedia.org/wiki/Crystal_Clear");
    }//GEN-LAST:event_lblCrystalClearMouseExited

    private void lblCrystalClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrystalClearMouseEntered
        lblCrystalClear.setText("<html>Crystal Clear - <u>http://commons.wikimedia.org/wiki/Crystal_Clear");
    }//GEN-LAST:event_lblCrystalClearMouseEntered

    private void lblCrystalClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrystalClearMouseClicked
        launchLink("http://commons.wikimedia.org/wiki/Crystal_Clear");
    }//GEN-LAST:event_lblCrystalClearMouseClicked

    private void lblJRubyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJRubyMouseExited
        lblJRuby.setText("JRuby - http://jruby.org/");
    }//GEN-LAST:event_lblJRubyMouseExited

    private void lblJRubyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJRubyMouseEntered
        lblJRuby.setText("<html>JRuby - <u>http://jruby.org/");
    }//GEN-LAST:event_lblJRubyMouseEntered

    private void lblJRubyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJRubyMouseClicked
        launchLink("http://jruby.org/");
    }//GEN-LAST:event_lblJRubyMouseClicked

    private void lblAFMLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAFMLinkMouseExited
        lblAFMLink.setText("https://github.com/TW2/Feuille");//http://code.google.com/p/feuille/
    }//GEN-LAST:event_lblAFMLinkMouseExited

    private void lblAFMLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAFMLinkMouseEntered
        lblAFMLink.setText("<html><u>https://github.com/TW2/Feuille");//http://code.google.com/p/feuille/
    }//GEN-LAST:event_lblAFMLinkMouseEntered

    private void lblAFMLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAFMLinkMouseClicked
        launchLink("https://github.com/TW2/Feuille");//http://code.google.com/p/feuille/
    }//GEN-LAST:event_lblAFMLinkMouseClicked

    private void lblAFMMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAFMMessageMouseClicked
        dispose();
    }//GEN-LAST:event_lblAFMMessageMouseClicked

    private void lblAssFxMakerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAssFxMakerMouseClicked
        dispose();
    }//GEN-LAST:event_lblAssFxMakerMouseClicked

    private void lblJFreeChartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJFreeChartMouseClicked
        launchLink("http://www.jfree.org/jfreechart/");
    }//GEN-LAST:event_lblJFreeChartMouseClicked

    private void lblJFreeChartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJFreeChartMouseEntered
        lblJFreeChart.setText("<html>JFreeChart - <u>http://www.jfree.org/jfreechart/");
    }//GEN-LAST:event_lblJFreeChartMouseEntered

    private void lblJFreeChartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJFreeChartMouseExited
        lblJFreeChart.setText("JFreeChart - http://www.jfree.org/jfreechart/");
    }//GEN-LAST:event_lblJFreeChartMouseExited

    private void lblROMEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblROMEMouseClicked
        launchLink("https://rometools.jira.com/wiki/display/ROME/Home");
    }//GEN-LAST:event_lblROMEMouseClicked

    private void lblROMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblROMEMouseEntered
        lblROME.setText("<html>ROME - <u>https://rometools.jira.com/wiki/display/ROME/Home");
    }//GEN-LAST:event_lblROMEMouseEntered

    private void lblROMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblROMEMouseExited
        lblROME.setText("ROME - https://rometools.jira.com/wiki/display/ROME/Home");
    }//GEN-LAST:event_lblROMEMouseExited

    private void lblJMFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJMFMouseClicked
        launchLink("http://www.oracle.com/technetwork/java/javase/download-142937.html");
    }//GEN-LAST:event_lblJMFMouseClicked

    private void lblJMFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJMFMouseEntered
        lblJMF.setText("<html>JMF - <u>http://www.oracle.com/technetwork/java/javase/download-142937.html");
    }//GEN-LAST:event_lblJMFMouseEntered

    private void lblJMFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJMFMouseExited
        lblJMF.setText("JMF - http://www.oracle.com/technetwork/java/javase/download-142937.html");
    }//GEN-LAST:event_lblJMFMouseExited

    private void lblJDOMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJDOMMouseClicked
        launchLink("http://www.jdom.org/");
    }//GEN-LAST:event_lblJDOMMouseClicked

    private void lblJDOMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJDOMMouseEntered
        lblJDOM.setText("<html>JDOM - <u>http://www.jdom.org/");
    }//GEN-LAST:event_lblJDOMMouseEntered

    private void lblJDOMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJDOMMouseExited
        lblJDOM.setText("JDOM - http://www.jdom.org/");
    }//GEN-LAST:event_lblJDOMMouseExited

    private void lblFreefontMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFreefontMouseClicked
        launchLink("http://savannah.gnu.org/projects/freefont/");
    }//GEN-LAST:event_lblFreefontMouseClicked

    private void lblFreefontMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFreefontMouseEntered
        lblFreefont.setText("<html>Free UCS Outline Fonts - <u>http://savannah.gnu.org/projects/freefont/");
    }//GEN-LAST:event_lblFreefontMouseEntered

    private void lblFreefontMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFreefontMouseExited
        lblFreefont.setText("Free UCS Outline Fonts - http://savannah.gnu.org/projects/freefont/");
    }//GEN-LAST:event_lblFreefontMouseExited

    /** <p>Launch the selected link and open a browser.<br />
     * Lance le lien sélectionné et ou un navigateur.</p> */
    private void launchLink(String link){
        boolean hasResult = true;
        if(java.awt.Desktop.isDesktopSupported()){
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
            if(desktop.isSupported(java.awt.Desktop.Action.BROWSE)){
                try {
                    try {
                        desktop.browse(new java.net.URI(link));
                    } catch (java.io.IOException ex) {hasResult = false;}
                } catch (java.net.URISyntaxException ex) {hasResult = false;}
            }else{
                hasResult = false;
            }
        }else{
            hasResult = false;
        }
        if(hasResult==false){
            java.util.Properties sys = System.getProperties();
            String os = sys.getProperty("os.name").toLowerCase();
            try {
                if(os.contains("windows")==true){
                    Process proc = Runtime.getRuntime().exec("cmd /c start "+link);
                }else{
                    Process proc = Runtime.getRuntime().exec("start "+link);
                }
            } catch (java.io.IOException e) {
                // unsupported
            }
        }        
    }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AboutDialog dialog = new AboutDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAFMLink;
    private javax.swing.JLabel lblAFMMessage;
    private javax.swing.JLabel lblAssFxMaker;
    private javax.swing.JLabel lblCrystalClear;
    private javax.swing.JLabel lblCurveCreator;
    private javax.swing.JLabel lblFreefont;
    private javax.swing.JLabel lblJDOM;
    private javax.swing.JLabel lblJFreeChart;
    private javax.swing.JLabel lblJMF;
    private javax.swing.JLabel lblJRuby;
    private javax.swing.JLabel lblJSyntaxPane;
    private javax.swing.JLabel lblJython;
    private javax.swing.JLabel lblROME;
    private javax.swing.JLabel lblUsedByAFM;
    // End of variables declaration//GEN-END:variables

}
