shape.line=Line
shape.quadratic=Quadratic Bézier
shape.cubic=Cubic Bézier
shape.spline=Bézier Spline
shape.grip=Grip
shape.thickness=Thickness
shape.point=Point
shape.control.point=Control point

menu.file=File
menu.quit=Quit
menu.module=Modules
menu.drawing=Sketchpad
menu.draw.mod=Show sketchpad
menu.open.drawing=Open an existing drawing...
menu.save.drawing=Save the drawing...
menu.clear.drawing=Clear sketchpad
menu.editor.ass=ASS editor
menu.editor.ass.mod=Show ASS editor

dialog.ok=OK
dialog.cancel=Cancel
dialog.settings=Settings
dialog.settings.tab.name.db=Database
dialog.settings.lbl.default=<html>Default settings:&nbsp;
dialog.settings.cbx.default=Use default settings
dialog.settings.lbl.audio.db=<html>Names of SQLite audio databases:&nbsp;
dialog.settings.cbx.audio.db=Different for each project
dialog.settings.lbl.assa.db=<html>Names of SQLite ASS databases:&nbsp;
dialog.settings.cbx.assa.db=Different for each project
dialog.settings.lbl.manage.name=Manage project
dialog.settings.btn.add=Add
dialog.settings.btn.change=Change
dialog.settings.btn.remove=Remove