/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package feuille.welcome;

/**
 *
 * @author The Wingate 2940
 */
public class AtomMiniPanel extends javax.swing.JPanel {

    /**
     * Creates new form AtomMiniPanel
     */
    public AtomMiniPanel() {
        initComponents();
    }
    
    public AtomMiniPanel(String title, String link) {
        initComponents();
        lblTitle.setText(title);
        lblLink.setText(link);
    }
    
    public void setTitle(String title){
        lblTitle.setText(title);
    }
    
    public void setLink(String link){
        lblLink.setText(link);
    }
    
    
    /** <p>Launch the selected link and open a browser.<br />
     * Lance le lien sélectionné et ou un navigateur.</p> */
    private void launchLink(String link){
        boolean hasResult = true;
        if(java.awt.Desktop.isDesktopSupported()){
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
            if(desktop.isSupported(java.awt.Desktop.Action.BROWSE)){
                try {
                    try {
                        desktop.browse(new java.net.URI(link));
                    } catch (java.io.IOException ex) {hasResult = false;}
                } catch (java.net.URISyntaxException ex) {hasResult = false;}
            }else{
                hasResult = false;
            }
        }else{
            hasResult = false;
        }
        if(hasResult==false){
            java.util.Properties sys = System.getProperties();
            String os = sys.getProperty("os.name").toLowerCase();
            try {
                if(os.contains("windows")==true){
                    Process proc = Runtime.getRuntime().exec("cmd /c start "+link);
                }else{
                    Process proc = Runtime.getRuntime().exec("start "+link);
                }
            } catch (java.io.IOException e) {
                // unsupported
            }
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblLink = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("jLabel1");

        lblLink.setForeground(new java.awt.Color(51, 51, 255));
        lblLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLink.setText("jLabel2");
        lblLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                    .addComponent(lblLink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLink)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLinkMouseClicked
        String s = lblLink.getText();
        launchLink(s);
    }//GEN-LAST:event_lblLinkMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLink;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
